/** Arabic copy for the new studio controls and project demonstrations. */
export const studioAr: Record<string, string> = {
  'Explore in 3D': 'استكشف بتقنية ثلاثية الأبعاد',
  'Conceptual demonstration': 'عرض توضيحي تصوري',
  'Interactive project demonstration': 'عرض تفاعلي للمشروع',
  'Camera view': 'زاوية العرض', 'Perspective': 'منظور', 'Front': 'أمامي', 'Top': 'علوي',
  'Zoom in': 'تكبير', 'Zoom out': 'تصغير',
  'Drag to rotate · Use view buttons to explore': 'اسحب للتدوير · استخدم أزرار العرض للاستكشاف',
  'Pause motion': 'إيقاف الحركة', 'Play motion': 'تشغيل الحركة', 'Auto-rotate': 'تدوير تلقائي', 'Reset view': 'إعادة ضبط العرض',
  'Retry 3D view': 'إعادة محاولة العرض ثلاثي الأبعاد', 'Load interactive 3D': 'تحميل العرض التفاعلي',
  'Preparing the interactive view…': 'جارٍ إعداد العرض التفاعلي…',
  'The 3D view could not load. You can still explore the project below.': 'تعذر تحميل العرض ثلاثي الأبعاد. يمكنك متابعة تفاصيل المشروع أدناه.',
  'Project illustration. The full case study is available below.': 'صورة توضيحية للمشروع. تتوفر دراسة الحالة كاملة أدناه.',
  'From the vehicle to the cloud': 'من المركبة إلى السحابة',
  'Inspect the enclosure, cellular module, carrier board and antenna of the MYMO2 tracker.': 'استكشف الغلاف ووحدة الاتصال الخلوي واللوحة والهوائي في جهاز تتبع MYMO2.',
  'Separate components': 'فصل المكونات', 'Assembled': 'مجمّع', 'Internal components': 'المكونات الداخلية', 'Exploded view': 'عرض المكونات منفصلة',
  'EC200U cellular module': 'وحدة الاتصال الخلوي EC200U', 'GNSS + BLE': 'GNSS + BLE', 'Vehicle harness': 'ضفيرة أسلاك المركبة',
  'A command becomes motion': 'أمر يتحول إلى حركة',
  'Move the target carriage along its rail and inspect the radio-controlled mechanism.': 'حرّك عربة الهدف على السكة واستكشف الآلية المتحكم بها لاسلكيًا.',
  'Carriage position': 'موضع العربة', 'Start of rail': 'بداية السكة', 'Midpoint': 'المنتصف', 'End of rail': 'نهاية السكة',
  'RF command link': 'رابط أوامر لاسلكي', 'Motor-driven carriage': 'عربة تعمل بمحرك', 'Rail travel': 'الحركة على السكة',
  'One update. Connected devices.': 'تحديث واحد وأجهزة متصلة',
  'Explore the firmware path from the configuration console through the server to the field device.': 'استكشف مسار البرنامج الثابت من واجهة الإعداد عبر الخادم إلى الجهاز الميداني.',
  'Separate system layers': 'فصل طبقات النظام', 'Connected system': 'نظام متصل', 'Delivery path': 'مسار التسليم', 'System layers': 'طبقات النظام',
  'BLE configuration': 'الإعداد عبر BLE', 'Firmware delivery': 'تسليم البرنامج الثابت', 'Field device': 'الجهاز الميداني',
  'Every device has a history': 'لكل جهاز تاريخ',
  'Inspect the physical devices behind inventory, provisioning, deployment and service records.': 'استكشف الأجهزة المرتبطة بسجلات المخزون والتهيئة والنشر والصيانة.',
  'Separate record stages': 'فصل مراحل السجلات', 'Device inventory': 'مخزون الأجهزة', 'Operational records': 'السجلات التشغيلية', 'Lifecycle stages': 'مراحل دورة الحياة',
  'SIM / IMEI': 'SIM / IMEI', 'Customer assignment': 'تخصيص العميل', 'Service history': 'سجل الصيانة',
  'From camera to classification': 'من الكاميرا إلى التصنيف',
  'Explore a camera and inference rig representing the video input and processing pipeline.': 'استكشف كاميرا ومنظومة استدلال تمثل إدخال الفيديو ومسار معالجته.',
  'Separate pipeline components': 'فصل مكونات مسار المعالجة', 'Camera rig': 'منظومة الكاميرا', 'Video input': 'إدخال الفيديو', 'Processing layers': 'طبقات المعالجة',
  '16-frame clips': 'مقاطع من 16 إطارًا', 'R(2+1)D-18': 'R(2+1)D-18', 'Temporal smoothing': 'التنعيم الزمني',
  'Signals into movement': 'إشارات تتحول إلى حركة',
  'Inspect the wheelchair conversion, control electronics and motor-driven wheels.': 'استكشف تعديل الكرسي المتحرك وإلكترونيات التحكم والعجلات المزودة بمحركات.',
  'Wheelchair': 'الكرسي المتحرك', 'Control electronics': 'إلكترونيات التحكم', 'Drive components': 'مكونات الدفع',
  'EEG → Raspberry Pi': 'EEG → Raspberry Pi', 'UART → Arduino': 'UART → Arduino', 'Motor drivers': 'دوائر قيادة المحركات',
  'Small device. Long journeys.': 'جهاز صغير لرحلات طويلة',
  'Open a compact collar tracker to reveal its battery, radio board and GPS antenna.': 'افتح جهاز تتبع الطوق الصغير لاستكشاف البطارية ولوحة الاتصال وهوائي GPS.',
  'Open tracker': 'فتح جهاز التتبع', 'Collar tracker': 'جهاز تتبع الطوق', 'Inside the enclosure': 'داخل الغلاف', 'Battery + radio': 'البطارية والاتصال اللاسلكي',
  'nRF9160': 'nRF9160', 'LTE-M / NB-IoT': 'LTE-M / NB-IoT', 'Low-power GPS': 'GPS منخفض الاستهلاك',
  'One website, every screen': 'موقع واحد لكل الشاشات',
  'Switch between the corporate pages on a desktop and mobile presentation of the responsive website.': 'تنقّل بين صفحات الشركة على عرض للحاسوب والهاتف يوضح التصميم المتجاوب.',
  'Website page': 'صفحة الموقع', 'Home': 'الرئيسية', 'About us': 'من نحن', 'Services': 'الخدمات', 'Careers': 'الوظائف',
  'Shared navigation': 'تنقل موحد', 'Responsive layouts': 'تخطيطات متجاوبة', 'Vanilla JavaScript': 'JavaScript دون أطر عمل',
  'A clearer path to care': 'طريق أوضح إلى الرعاية',
  'Explore the departments, appointment and contact views across desktop and mobile screens.': 'استكشف صفحات الأقسام والمواعيد والتواصل على شاشات الحاسوب والهاتف.',
  'Departments': 'الأقسام', 'Appointment': 'المواعيد', 'Contact': 'التواصل',
  'Department cards': 'بطاقات الأقسام', 'Appointment form': 'نموذج الموعد', 'Responsive navigation': 'تنقل متجاوب',
  'Tilt. Transmit. Drive.': 'إمالة ثم إرسال ثم حركة',
  'Change the tilt of the wearable controller and watch the robot respond to the wireless command.': 'غيّر إمالة وحدة التحكم القابلة للارتداء وشاهد استجابة الروبوت للأمر اللاسلكي.',
  'Controller tilt': 'إمالة وحدة التحكم', 'Steer left': 'توجيه لليسار', 'Forward': 'للأمام', 'Steer right': 'توجيه لليمين',
  'Accelerometer': 'مقياس التسارع', 'RF telemetry': 'القياس عن بعد لاسلكيًا', 'Arduino motor control': 'التحكم بالمحركات عبر Arduino',
  'Order at every intersection': 'تنظيم عند كل تقاطع',
  'Step through an illustrative four-way signal cycle, including amber and all-red clearance states.': 'تنقّل عبر دورة توضيحية لإشارات تقاطع رباعي تشمل الأصفر وحالات إيقاف جميع الاتجاهات.',
  'Signal phase': 'مرحلة الإشارة', 'N/S green': 'أخضر للشمال والجنوب', 'N/S amber': 'أصفر للشمال والجنوب', 'All red': 'جميع الإشارات حمراء', 'E/W green': 'أخضر للشرق والغرب', 'E/W amber': 'أصفر للشرق والغرب',
  'Finite state machine': 'آلة الحالات المحدودة', 'Clock-driven timing': 'توقيت محكوم بالساعة', 'Reset to all red': 'إعادة الضبط إلى الأحمر للجميع',
  'Behind the account record': 'ما وراء سجل الحساب',
  'Explore the manager and client console views and the binary-file persistence behind them.': 'استكشف واجهات المدير والعميل النصية وحفظ البيانات في الملفات الثنائية.',
  'Console view': 'واجهة وحدة التحكم', 'Manager': 'المدير', 'Client': 'العميل', 'Binary file': 'ملف ثنائي',
  'C++ console': 'واجهة نصية بلغة C++', 'Role-based operations': 'عمليات حسب الدور', 'File persistence': 'حفظ البيانات في الملفات',
  'Browse. Choose. Order.': 'تصفح واختر واطلب',
  'Follow an illustrative menu-to-order flow on a responsive storefront connected to its database.': 'تابع مسارًا توضيحيًا من القائمة إلى الطلب على واجهة متجاوبة متصلة بقاعدة بياناتها.',
  'Ordering step': 'خطوة الطلب', 'Menu': 'القائمة', 'Search': 'البحث', 'Order': 'الطلب',
  'PHP frontend + backend': 'واجهة وخلفية باستخدام PHP', 'Menu search': 'البحث في القائمة', 'MySQL records': 'سجلات MySQL',
};
